# Generated by Django 4.2.3 on 2023-07-28 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import places.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, editable=False, unique=True, verbose_name="slug"
                    ),
                ),
                (
                    "latitude",
                    places.models.CoordinateField(
                        decimal_places=6, max_digits=9, verbose_name="latitude"
                    ),
                ),
                (
                    "longitude",
                    places.models.CoordinateField(
                        decimal_places=6, max_digits=9, verbose_name="longitude"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="places",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
