# Generated by Django 4.2.3 on 2023-07-26 21:25

from django.db import migrations, models
import places.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="name")),
                (
                    "latitude",
                    places.models.CoordinateField(
                        decimal_places=6, max_digits=9, verbose_name="latitude"
                    ),
                ),
                (
                    "longitude",
                    places.models.CoordinateField(
                        decimal_places=6, max_digits=9, verbose_name="longitude"
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
            ],
        ),
    ]
