# Generated by Django 4.2.3 on 2023-07-20 09:27

from django.db import migrations, models
import media.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="",
                        validators=[
                            media.validators.ContentTypeValidator(["image", "video"])
                        ],
                        verbose_name="file",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(blank=True, max_length=64, verbose_name="type"),
                ),
            ],
        ),
    ]
