# Generated by Django 4.2.3 on 2023-07-28 04:14

from django.db import migrations, models
import django.db.models.deletion
import media.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        upload_to="",
                        validators=[
                            media.validators.MimeTypeValidator(["image/*", "video/*"])
                        ],
                        verbose_name="attachment",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        verbose_name="attachment type",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
