# Generated by Django 4.2.3 on 2023-07-22 09:19

from django.db import migrations, models
import media.validators


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                upload_to="",
                validators=[media.validators.MimeTypeValidator(["image/*", "video/*"])],
                verbose_name="file",
            ),
        ),
    ]
