# Generated by Django 4.2.3 on 2023-07-22 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_alter_media_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="file",
            new_name="attachment",
        ),
    ]
