# Generated by Django 4.2.3 on 2023-07-24 16:58

from django.db import migrations, models
import django.db.models.deletion
import media.validators


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media", "0003_rename_file_media_attachment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="content_type",
            new_name="attachment_type",
        ),
        migrations.AlterField(
            model_name="media",
            name="attachment_type",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="attachment type"
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="object_id",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="media",
            name="attachment",
            field=models.FileField(
                upload_to="",
                validators=[media.validators.MimeTypeValidator(["image/*", "video/*"])],
                verbose_name="attachment",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
