# Generated by Django 4.2.3 on 2023-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0004_media_file_type_media_object_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="object_id",
            field=models.PositiveIntegerField(),
        ),
    ]
