# Generated by Django 4.2.3 on 2023-07-24 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("media", "0005_alter_media_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
