# Generated by Django 4.2.3 on 2023-07-26 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0006_alter_media_content_type_alter_media_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="attachment_type",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                verbose_name="attachment type",
            ),
        ),
    ]
